// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupRolloutPrefs.extensions.fxmonitor.enabled", true);
user_pref("app.normandy.startupRolloutPrefs.network.cookie.cookieBehavior", 4);
user_pref("app.normandy.user_id", "91a0f1e0-3bc8-4041-816b-94a703c1da17");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1562590110);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1562590231);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1562678867);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1562679107);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1562678987);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1562679227);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1562590471);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1562590351);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contentblocking.introCount", 20);
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1560775596);
user_pref("browser.laterrun.bookkeeping.sessionCount", 10);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 80);
user_pref("browser.newtabpage.activity-stream.impressionId", "{8d6ffb03-1a74-4e7a-9673-be6fea715cda}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1562678847094");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1562680656094");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1562678843211");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1562682443211");
user_pref("browser.search.region", "MX");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190620092152");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1562678841");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20190620092152");
user_pref("browser.startup.homepage_override.mstone", "67.0.4");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1560775602829");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "67.0.4");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "ea7b97d483954703b6c97f5ce5acee24");
user_pref("extensions.blocklist.lastModified", "Mon, 08 Jul 2019 09:25:03 GMT");
user_pref("extensions.blocklist.pingCountTotal", 6);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1562590113);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20190620092152");
user_pref("extensions.lastAppVersion", "67.0.4");
user_pref("extensions.lastPlatformVersion", "67.0.4");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"3c03a1c7-24be-40d1-a1d4-f97bc684d931\",\"fxmonitor@mozilla.org\":\"61442cc6-cba3-4ecd-8fe9-a608ab16c77c\",\"screenshots@mozilla.org\":\"f3c9ffe2-ae97-4baf-a29d-484f3f29a9a7\",\"webcompat-reporter@mozilla.org\":\"5a25e3cd-a6dd-4fc2-b924-0616387be82d\",\"webcompat@mozilla.org\":\"1217a908-d6ce-4d7d-8c71-6b329a28055d\"}");
user_pref("idle.lastDailyNotification", 1562592105);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1560775628);
user_pref("media.gmp-gmpopenh264.version", "1.8.1");
user_pref("media.gmp-manager.buildID", "20190620092152");
user_pref("media.gmp-manager.lastCheck", 1562678876);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("permissions.eventTelemetry.salt", "{131a1342-d628-4958-b0fa-b94d6136e220}");
user_pref("places.database.lastMaintenance", 1562592105);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.remote_settings.intermediates.checked", 1562679053);
user_pref("security.sandbox.content.tempDirSuffix", "d68043ac-2e9e-4cc9-b417-c997c4aef7c0");
user_pref("security.sandbox.plugin.tempDirSuffix", "90202d52-b3b2-4c17-9453-18229b746b69");
user_pref("services.blocklist.addons.checked", 1562679053);
user_pref("services.blocklist.gfx.checked", 1562679053);
user_pref("services.blocklist.onecrl.checked", 1562679053);
user_pref("services.blocklist.pinning.checked", 1562679053);
user_pref("services.blocklist.plugins.checked", 1562679053);
user_pref("services.settings.clock_skew_seconds", -48);
user_pref("services.settings.last_etag", "\"1562673628501\"");
user_pref("services.settings.last_update_seconds", 1562679275);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1562679053);
user_pref("services.settings.main.hijack-blocklists.last_check", 1562679053);
user_pref("services.settings.main.language-dictionaries.last_check", 1562679053);
user_pref("services.settings.main.onboarding.last_check", 1562679053);
user_pref("services.settings.main.sites-classification.last_check", 1562679053);
user_pref("services.settings.main.tippytop.last_check", 1562679053);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1562679053);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1560777330);
user_pref("toolkit.startup.last_success", 1562678831);
user_pref("toolkit.telemetry.cachedClientID", "996a7dec-d775-4bee-adea-b25eea01f25f");
user_pref("toolkit.telemetry.previousBuildID", "20190620092152");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
